services:
  - type: web
    name: ucampus-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8081"
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d4k6jnc9c44c73eoodc0-a.oregon-postgres.render.com:5432/ucampus_zy03
      - key: DB_USERNAME
        value: ucampus_zy03_user
      - key: DB_PASSWORD
        value: M5HWVb2qKiDXSzxjaqFulwYlQBScWSGV
